base_locale: en

data:
  read:
    - config/locales/administrate-field-nested_has_many.%{locale}.yml

ignore:
  - 'administrate.fields.has_many.*'
  - 'cocoon.defaults.*'
  - 'cocoon.foo/students.*'
  - 'cocoon.students.*'
